apiVersion: v1
kind: Service
metadata:
  name: fifa-worldcup-api-service # a DNS-1035 label must consist of lower case alphanumeric characters or '-'
  labels:
    app: FifaWorldCupApi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: FifaWorldCupApi