apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifa.worldcup.api.deployment
  labels:
    app: FifaWorldCupApi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: FifaWorldCupApi
  template: #Pod
    metadata:
      labels:
        app: FifaWorldCupApi
    spec:
      containers:
        - name: fifa-world-cup-container
          image: fifaworldcup:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP